### PR TITLE
Fix typo in privacy policy heading (fix #643)

### LINKED ISSUE #643: Typo in privacy policy
The penultimate heading in the privacy policy, accessed by clicking the info icon on the right of the screen, reads *What else do we want you know?* has a missing *to* at the end.

### PR DESCRIPTION
**Pull request by fmarier**

### CODE REVIEW

**Comment by monicachew** [comment]
We should probably just remove the policy and point to the online version. It doesn't make sense to have to keep these in sync.

https://www.mozilla.org/en-US/privacy/

**Comment by fmarier** [comment]
In fact, I think we might even be able to remove our privacy policy entirely if we talk to Jishnu about it, given that we took the reporting functionality out.

So maybe we should keep it in there until we check with Jishnu?

**Comment by monicachew** [comment]
I guess one can suppose that the policy applies also to things like AMO
stats on number of installs, etc. that are orthogonal to the data
collection piece. I think it is OK to leave it in in link form.

**Comment by fmarier** [comment]
I've filed a follow-up bug for that: #650.

**Comment by monicachew** [comment]
Thanks!

**Pull request merged**
